### ISSUE TITLE
"上游"的资源文件有更新

### ISSUE THREAD

**Issue by kasumi22** [SummonHIM/april-bang-dream-2022-mirror#2]
修了一句台词的错误，乐😂
新的资源包文件可以参考[此处: https://web.archive.org/web/20220501201243/https://april-bang-dream.bushimo.jp/artemis.data](https://web.archive.org/web/20220501201243/https://april-bang-dream.bushimo.jp/artemis.data)

![image](https://user-images.githubusercontent.com/102806605/166181435-970c9a60-ffd8-49e7-8866-1ff8d60d2935.png)

**Comment by SummonHIM** [comment]
草 居然还有变动 偷懒武士道

现在就下载

**Comment by SummonHIM** [comment]
还有请问下怎么封包成pfs呢

我弄了一个[Workflow](https://github.com/SummonHIM/april-bang-dream-2022-mirror/blob/Artemis/.github/workflows/pack.yml)。但是实际封包却报 “Caught a C++ exception. filesystem error: Cannot convert character sequence: Invalid or incomplete multibyte or wide character”（[详细Log|Pack folder into Artemis pfs file](https://github.com/SummonHIM/april-bang-dream-2022-mirror/runs/6034956842?check_suite_focus=true)）

**Comment by kasumi22** [comment]
有可能是[nextgal/pfs_upk](https://github.com/nextgal/pfs_upk)的问题，改了一下就能用了
[Log](https://github.com/kasumi22/april-bang-dream-2022-mirror/runs/6254051402)
刚试着给人家提了个issue，不知道能不能行

**Comment by SummonHIM** [comment]
尝试着用你的pfs_upk编译确实可以 但是包出来的档似乎并不能读取 [（示例）](https://summonhim.github.io/april-bang-dream-2022-mirror/test-chs/artemis.html)

使用Garbro也无法打开文件夹 只能打开system.ini

![屏幕截图 2022-05-02 174222](https://user-images.githubusercontent.com/33192611/166215276-5b2a9261-fe55-4a3e-a123-8683e29ecd0a.png)

不知是否编码问题？

ps: 用的 [test-chs](https://github.com/SummonHIM/april-bang-dream-2022-mirror/tree/test-chs) 分支包的 把之前做的几个ui（[pc/ja/conf](https://github.com/SummonHIM/april-bang-dream-2022-mirror/tree/test-chs/Unpack/pc/ja/conf)）包了进去

**Comment by kasumi22** [comment]
改了一下，这回能行吗

**Comment by SummonHIM** [comment]
可以了 多谢大佬
